name: deployment

on:
  push:
    branches:
      - test

run-name: Deploying to ${{ github.ref_name }} by ${{ github.actor }}

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: github ref
        run: |
          echo "github ref: ${{ github.ref }} , github ref_name: ${{ github.ref_name }}
