name: deploy to uat

on:
  push:
    paths:
      - force-app/**
    branches:
      - dev

jobs:
  deploy-to-uat:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz

          mkdir ~/sf

          tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1

          echo "$HOME/sf/bin" >> $GITHUB_PATH

          ~/sf/bin/sf version

      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.PROD_URL}} > ./PROD_URL.txt

      - name: Authenticate to target Org
        run: sf org login sfdx-url --sfdx-url-file ./PROD_URL.txt --set-default --alias myOrg

      - name: Validation - run all tests
        run: sf project deploy start --source-dir force-app --target-org myOrg --json